site_name: Citation Report Docs
site_description: Regex formula of Philippine Supreme Court citations in report format, i.e. SCRA, PHIL, OFFG
site_url: https://lawsql.com
site_author: Marcelino Veloso III
repo_url: https://github.com/justmars/citation-report
theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  version:
    provider: mike
nav:
- index.md
plugins:
  - autorefs
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            show_root_toc_entry: false
            show_category_heading: true
            show_source: true
            heading_level: 3
  - search:
      lang: en
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
